// https://material-foundation.github.io/material-theme-builder/

const COMMON = {
  // customRoundness: (v: number | "full") =>
  //   v === "full" ? Number.MAX_SAFE_INTEGER : 4 * v,
  roundness: {
    none: 0,
    xs: 2,
    sm: 4,
    md: 6,
    lg: 8,
    xl: 12,
    "2xl": 16,
    "3xl": 24,
    "4xl": 32,
    full: Number.MAX_SAFE_INTEGER,
  },
  // https://tailwindcss.com/docs/font-weight
  fontWeight: {
    thin: "100",
    extraLight: "200",
    light: "300",
    regular: "400",
    medium: "500",
    semiBold: "600",
    bold: "700",
    extraBold: "800",
    black: "900",
  },
};

export const THEMES = {
  light: {
    ...COMMON,
    colors: {
      primary: "#725C0C",
      surfaceTint: "#725C0C",
      onPrimary: "#FFFFFF",
      primaryContainer: "#FFE088",
      onPrimaryContainer: "#574500",
      secondary: "#695D3F",
      onSecondary: "#FFFFFF",
      secondaryContainer: "#F1E1BB",
      onSecondaryContainer: "#50462A",
      tertiary: "#46664B",
      onTertiary: "#FFFFFF",
      tertiaryContainer: "#C8ECC9",
      onTertiaryContainer: "#2F4E34",
      error: "#BA1A1A",
      onError: "#FFFFFF",
      errorContainer: "#FFDAD6",
      onErrorContainer: "#93000A",
      background: "#FFF8F0",
      onBackground: "#1F1B13",
      surface: "#FFF8F0",
      onSurface: "#1F1B13",
      surfaceVariant: "#EBE1CF",
      onSurfaceVariant: "#4C4639",
      outline: "#7D7667",
      outlineVariant: "#CFC6B4",
      shadow: "#000000",
      scrim: "#000000",
      inverseSurface: "#343027",
      inverseOnSurface: "#F8F0E2",
      inversePrimary: "#E2C46D",
      primaryFixed: "#FFE088",
      onPrimaryFixed: "#241A00",
      primaryFixedDim: "#E2C46D",
      onPrimaryFixedVariant: "#574500",
      secondaryFixed: "#F1E1BB",
      onSecondaryFixed: "#221B04",
      secondaryFixedDim: "#D4C5A1",
      onSecondaryFixedVariant: "#50462A",
      tertiaryFixed: "#C8ECC9",
      onTertiaryFixed: "#03210C",
      tertiaryFixedDim: "#ACCFAE",
      onTertiaryFixedVariant: "#2F4E34",
      surfaceDim: "#E1D9CC",
      surfaceBright: "#FFF8F0",
      surfaceContainerLowest: "#FFFFFF",
      surfaceContainerLow: "#FBF3E5",
      surfaceContainer: "#F5EDDF",
      surfaceContainerHigh: "#EFE7D9",
      surfaceContainerHighest: "#EAE1D4",

      // these two I added by hand (it's the onSurface color)
      surfaceDisabled: "rgba(31, 27, 19, 0.12)",
      onSurfaceDisabled: "rgba(31, 27, 19, 0.38)",
    },
  },
  dark: {
    ...COMMON,
    colors: {
      primary: "#E2C46D",
      surfaceTint: "#E2C46D",
      onPrimary: "#3C2F00",
      primaryContainer: "#574500",
      onPrimaryContainer: "#FFE088",
      secondary: "#D4C5A1",
      onSecondary: "#393016",
      secondaryContainer: "#50462A",
      onSecondaryContainer: "#F1E1BB",
      tertiary: "#ACCFAE",
      onTertiary: "#19371F",
      tertiaryContainer: "#2F4E34",
      onTertiaryContainer: "#C8ECC9",
      error: "#FFB4AB",
      onError: "#690005",
      errorContainer: "#93000A",
      onErrorContainer: "#FFDAD6",
      background: "#16130B",
      onBackground: "#EAE1D4",
      surface: "#16130B",
      onSurface: "#EAE1D4",
      surfaceVariant: "#4C4639",
      onSurfaceVariant: "#CFC6B4",
      outline: "#989080",
      outlineVariant: "#4C4639",
      shadow: "#000000",
      scrim: "#000000",
      inverseSurface: "#EAE1D4",
      inverseOnSurface: "#343027",
      inversePrimary: "#725C0C",
      primaryFixed: "#FFE088",
      onPrimaryFixed: "#241A00",
      primaryFixedDim: "#E2C46D",
      onPrimaryFixedVariant: "#574500",
      secondaryFixed: "#F1E1BB",
      onSecondaryFixed: "#221B04",
      secondaryFixedDim: "#D4C5A1",
      onSecondaryFixedVariant: "#50462A",
      tertiaryFixed: "#C8ECC9",
      onTertiaryFixed: "#03210C",
      tertiaryFixedDim: "#ACCFAE",
      onTertiaryFixedVariant: "#2F4E34",
      surfaceDim: "#16130B",
      surfaceBright: "#3D392F",
      surfaceContainerLowest: "#110E07",
      surfaceContainerLow: "#1F1B13",
      surfaceContainer: "#231F17",
      surfaceContainerHigh: "#2D2A21",
      surfaceContainerHighest: "#38342B",

      // these two I added by hand (it's the onSurface color)
      surfaceDisabled: "rgba(234, 225, 212, 0.12)",
      onSurfaceDisabled: "rgba(234, 225, 212, 0.38)",
    },
  },
} as const;
